export type {
  DomainPack,
  OrgProfile,
  PersonProfile,
  ArticleSchemaPolicy,
  LlmsTxtConfig,
  LlmsTxtSection,
  ScoringConfig,
  SeoConfig,
  GeoConfig,
  GeoCheckDef,
  CitationConfig,
  AeoConfig,
  AeoQuery,
  CompetitorsConfig,
  CompetitorEntry,
  StrategyConfig,
  StrategyThresholds,
  StrategyRefererGroups,
  DraftingConfig,
  AmplifyConfig,
  AmplifyChannel,
  CarouselScheme,
  MediaConfig,
  NarrationConfig,
  HeroImageConfig,
  PodcastConfig,
  PodcastTrailer,
  VoiceSettings,
  PronunciationOverride,
  AbbreviationExpansion,
  AnalyticsConfig,
  AiBot,
  RefererChannelRule,
  EntityPresenceConfig,
  EntityPresenceSource,
  EnginePresenceAffinity,
  MentionConsistencyTargets,
} from './types.js';

export { domainPackSchema, type DomainPackInput } from './schema.js';
export {
  defaultScoringConfig,
  defaultGeoConfig,
  defaultSeoConfig,
  defaultStrategyConfig,
  defaultDraftingConfig,
  defaultAmplifyConfig,
  defaultMediaConfig,
  defaultAnalyticsConfig,
  defaultEntityPresenceConfig,
} from './defaults.js';
export {
  loadDomainPack,
  validateDomainPack,
  resolveConfigPath,
  defineDomainPack,
  type ValidateResult,
} from './load.js';
